2018-09-29 17:44:51,449 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-29 17:44:51,449 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-29 17:44:51,449 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-29 17:44:51,449 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-29 17:44:51,488 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-29 17:44:51,488 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-29 17:44:51,489 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-29 17:44:51,489 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-29 17:45:06,576 -       nornir -    ERROR -      start() - access2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/napalm_connection.py", line 53, in napalm_connection
    host.connections["napalm"].open()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/napalm/ios/ios.py", line 138, in open
    netmiko_optional_args=self.netmiko_optional_args,
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/napalm/base/base.py", line 82, in _netmiko_open
    **netmiko_optional_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

2018-09-29 17:45:06,576 -       nornir -    ERROR -      start() - access2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/napalm_connection.py", line 53, in napalm_connection
    host.connections["napalm"].open()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/napalm/ios/ios.py", line 138, in open
    netmiko_optional_args=self.netmiko_optional_args,
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/napalm/base/base.py", line 82, in _netmiko_open
    **netmiko_optional_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

2018-09-29 17:45:06,620 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-29 17:45:06,620 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-29 17:45:06,621 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-29 17:45:06,621 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-29 17:45:06,637 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-29 17:45:06,637 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-29 17:49:31,540 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-29 17:49:31,540 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-29 17:49:31,541 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using Napalm'}
2018-09-29 17:49:31,541 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using Napalm'}
2018-09-29 17:49:31,562 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-29 17:49:31,562 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-29 17:49:31,563 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-29 17:49:31,563 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-29 17:49:37,054 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-29 17:49:37,054 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-29 17:49:37,055 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-29 17:49:37,055 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-29 17:49:37,072 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-29 17:49:37,072 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-29 17:49:37,073 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-29 17:49:37,073 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-29 18:41:53,045 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 18:41:53,045 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 18:41:53,050 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using netmiko'}
2018-09-29 18:41:53,050 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using netmiko'}
2018-09-29 18:41:53,067 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 18:41:53,067 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 18:41:53,069 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 18:41:53,069 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 18:41:53,073 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'optional_args'

2018-09-29 18:41:53,073 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'optional_args'

2018-09-29 18:41:53,074 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'optional_args'

2018-09-29 18:41:53,074 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'optional_args'

2018-09-29 18:41:53,184 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 18:41:53,184 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 18:41:53,184 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 18:41:53,184 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 18:42:37,921 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 18:42:37,921 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 18:42:37,921 -       nornir -    DEBUG -        run() - {'name': 'Connect using netmiko', 'netmiko_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-29 18:42:37,921 -       nornir -    DEBUG -        run() - {'name': 'Connect using netmiko', 'netmiko_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-29 18:42:37,944 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 18:42:37,945 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 18:42:37,945 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 18:42:37,944 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 18:42:37,946 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'netmiko_args'

2018-09-29 18:42:37,946 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'netmiko_args'

2018-09-29 18:42:37,947 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'netmiko_args'

2018-09-29 18:42:37,947 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'netmiko_args'

2018-09-29 18:42:38,049 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 18:42:38,049 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 18:42:38,049 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 18:42:38,049 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 18:49:39,886 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 18:49:39,886 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 18:49:39,886 -       nornir -    DEBUG -        run() - {'name': 'Connect using netmiko'}
2018-09-29 18:49:39,886 -       nornir -    DEBUG -        run() - {'name': 'Connect using netmiko'}
2018-09-29 18:49:39,903 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 18:49:39,903 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 18:49:39,905 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 18:49:39,905 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 18:51:20,013 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 743, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.255.0.4:22

2018-09-29 18:51:20,013 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 743, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.255.0.4:22

2018-09-29 18:51:20,013 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 743, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.255.0.5:22

2018-09-29 18:51:20,013 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 743, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.255.0.5:22

2018-09-29 18:51:20,123 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 18:51:20,123 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 18:51:20,124 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 18:51:20,124 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 19:01:35,178 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 19:01:35,178 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 19:01:35,178 -       nornir -    DEBUG -        run() - {'name': 'Connect using netmiko', 'ssh_config_file': '/home/vagrant/.ssh/config'}
2018-09-29 19:01:35,178 -       nornir -    DEBUG -        run() - {'name': 'Connect using netmiko', 'ssh_config_file': '/home/vagrant/.ssh/config'}
2018-09-29 19:01:35,194 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 19:01:35,194 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 19:01:35,197 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 19:01:35,197 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 19:01:50,287 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

2018-09-29 19:01:50,287 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

2018-09-29 19:01:50,288 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

2018-09-29 19:01:50,288 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 738, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

2018-09-29 19:01:50,412 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 19:01:50,412 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 19:01:50,413 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 19:01:50,413 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 19:03:09,682 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 19:03:09,682 -       nornir -     INFO -        run() - Running task 'Connect using netmiko' with num_workers: 100
2018-09-29 19:03:09,682 -       nornir -    DEBUG -        run() - {'ssh_config_file': '/home/vagrant/.ssh/config', 'device_type': 'cisco_ios_telnet', 'name': 'Connect using netmiko'}
2018-09-29 19:03:09,682 -       nornir -    DEBUG -        run() - {'ssh_config_file': '/home/vagrant/.ssh/config', 'device_type': 'cisco_ios_telnet', 'name': 'Connect using netmiko'}
2018-09-29 19:03:09,698 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 19:03:09,698 -       nornir -     INFO -      start() - router1: Connect using netmiko: running task
2018-09-29 19:03:09,699 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 19:03:09,699 -       nornir -     INFO -      start() - router2: Connect using netmiko: running task
2018-09-29 19:04:49,825 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 218, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 727, in establish_connection
    self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

2018-09-29 19:04:49,825 -       nornir -    ERROR -      start() - router1: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 218, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 727, in establish_connection
    self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

2018-09-29 19:04:49,825 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 218, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 727, in establish_connection
    self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

2018-09-29 19:04:49,825 -       nornir -    ERROR -      start() - router2: Traceback (most recent call last):
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/core/task.py", line 62, in start
    r = self.task(self, **self.params)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/nornir/plugins/tasks/connections/netmiko_connection.py", line 36, in netmiko_connection
    host.connections["netmiko"] = ConnectHandler(**netmiko_connection_args)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 218, in __init__
    self.establish_connection()
  File "/home/vagrant/NetAutoExample1/venv/lib/python3.5/site-packages/netmiko/base_connection.py", line 727, in establish_connection
    self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

2018-09-29 19:04:49,909 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 19:04:49,909 -       nornir -     INFO -        run() - Running task 'netmiko_send_config' with num_workers: 100
2018-09-29 19:04:49,910 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-29 19:04:49,910 -       nornir -    DEBUG -        run() - {'config_commands': 'crypto key generate rsa modu 2048'}
2018-09-30 08:00:53,587 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:00:53,587 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:00:53,588 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 08:00:53,588 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 08:00:53,649 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:00:53,649 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:00:53,649 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:00:53,649 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:03:45,954 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:03:45,954 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:03:45,954 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using Napalm'}
2018-09-30 08:03:45,954 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using Napalm'}
2018-09-30 08:03:46,054 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:03:46,054 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:03:46,084 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:03:46,084 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:03:51,469 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:03:51,469 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:03:51,470 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:03:51,470 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:03:51,491 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:03:51,491 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:03:51,492 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:03:51,492 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:04:13,735 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:04:13,735 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:04:13,736 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using Napalm'}
2018-09-30 08:04:13,736 -       nornir -    DEBUG -        run() - {'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}, 'name': 'Connect using Napalm'}
2018-09-30 08:04:13,904 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:04:13,904 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:04:13,912 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:04:13,912 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:04:19,405 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:04:19,405 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:04:19,406 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:04:19,406 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:04:19,424 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:04:19,424 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:04:19,425 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:04:19,425 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:04:38,893 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:04:38,893 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:04:38,893 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 08:04:38,893 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 08:04:39,016 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:04:39,016 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:04:39,017 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:04:39,017 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:04:44,736 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:04:44,736 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:04:44,736 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:04:44,736 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:04:44,756 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:04:44,756 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:04:44,757 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:04:44,757 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:24:56,006 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:24:56,006 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 08:24:56,007 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 08:24:56,007 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 08:24:56,091 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:24:56,091 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 08:24:56,092 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:24:56,092 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 08:25:01,615 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:25:01,615 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 08:25:01,615 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:25:01,615 -       nornir -    DEBUG -        run() - {'getters': ['get_interfaces']}
2018-09-30 08:25:01,635 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:25:01,635 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 08:25:01,636 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 08:25:01,636 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 09:09:30,297 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 09:09:30,297 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 09:09:30,298 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 09:09:30,298 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 09:09:30,318 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 09:09:30,318 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 09:09:30,321 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 09:09:30,321 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 09:09:35,874 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 09:09:35,874 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 09:09:35,874 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-30 09:09:35,874 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-30 09:09:35,892 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 09:09:35,892 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 09:09:35,892 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 09:09:35,892 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 09:10:57,267 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 09:10:57,267 -       nornir -     INFO -        run() - Running task 'Connect using Napalm' with num_workers: 100
2018-09-30 09:10:57,267 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 09:10:57,267 -       nornir -    DEBUG -        run() - {'name': 'Connect using Napalm', 'optional_args': {'ssh_config_file': '/home/vagrant/.ssh/config'}}
2018-09-30 09:10:57,282 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 09:10:57,282 -       nornir -     INFO -      start() - access2: Connect using Napalm: running task
2018-09-30 09:10:57,286 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 09:10:57,286 -       nornir -     INFO -      start() - access1: Connect using Napalm: running task
2018-09-30 09:11:02,847 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 09:11:02,847 -       nornir -     INFO -        run() - Running task 'napalm_get' with num_workers: 100
2018-09-30 09:11:02,847 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-30 09:11:02,847 -       nornir -    DEBUG -        run() - {'getters': ['get_mac_address_table']}
2018-09-30 09:11:02,868 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 09:11:02,868 -       nornir -     INFO -      start() - access2: napalm_get: running task
2018-09-30 09:11:02,868 -       nornir -     INFO -      start() - access1: napalm_get: running task
2018-09-30 09:11:02,868 -       nornir -     INFO -      start() - access1: napalm_get: running task
